### ISSUE TITLE
Sign-In Screen

### ISSUE THREAD

**Issue by JulioLeiteSilva** [JulioLeiteSilva/filmo-frontend#1]
### TODO:

- [x] Tela Seguindo protótipo do figma
- [x] Desenvolver a lógica de validação dos campos
- [x] Integrar com a API

Imagem base:
![image](https://github.com/JulioLeiteSilva/filmo-frontend/assets/104083214/d4d1619c-a8a0-4b63-8d2b-f7a4c048001e)

**Comment by JulioLeiteSilva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desenvolver tela de login](https://trello.com/c/gHKK4U39/6-desenvolver-tela-de-login)
