### ISSUE TITLE
Sign-Up Screen

### ISSUE THREAD

**Issue by JulioLeiteSilva** [JulioLeiteSilva/filmo-frontend#2]
### TODO:

- [x] Tela Seguindo protótipo do figma
- [x] Desenvolver a lógica de validação dos campos
- [x] Integrar com a API

Imagem base:
![image](https://github.com/JulioLeiteSilva/filmo-frontend/assets/104083214/7056b29a-89e6-4789-a863-b14353f474e4)

**Comment by JulioLeiteSilva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desenvolver tela de cadastro](https://trello.com/c/UvttVIEq/7-desenvolver-tela-de-cadastro)
