### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by JulioLeiteSilva** [JulioLeiteSilva/filmo-frontend#3]
### TODO:

- [ ] Desenvolver tela utilizando o protótipo do figma como base
- [ ] Integrar com API
- [ ] Utilizar storage local

Imagem base:
![image](https://github.com/JulioLeiteSilva/filmo-frontend/assets/104083214/4b6dba6e-ea22-45d9-aea4-211bba94092e)
